// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: RpcPacket.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_RpcPacket_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_RpcPacket_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3021000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3021004 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/generated_enum_reflection.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_RpcPacket_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_RpcPacket_2eproto {
  static const uint32_t offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_RpcPacket_2eproto;
namespace RPC_PACKET {
class PB_CS_NOTIFY;
struct PB_CS_NOTIFYDefaultTypeInternal;
extern PB_CS_NOTIFYDefaultTypeInternal _PB_CS_NOTIFY_default_instance_;
class PB_SC_NOTIFY;
struct PB_SC_NOTIFYDefaultTypeInternal;
extern PB_SC_NOTIFYDefaultTypeInternal _PB_SC_NOTIFY_default_instance_;
}  // namespace RPC_PACKET
PROTOBUF_NAMESPACE_OPEN
template<> ::RPC_PACKET::PB_CS_NOTIFY* Arena::CreateMaybeMessage<::RPC_PACKET::PB_CS_NOTIFY>(Arena*);
template<> ::RPC_PACKET::PB_SC_NOTIFY* Arena::CreateMaybeMessage<::RPC_PACKET::PB_SC_NOTIFY>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace RPC_PACKET {

enum RPC_PROTOCOL : int {
  CS_NOTIFY = 0,
  SC_NOTIFY = 1,
  RPC_PROTOCOL_INT_MIN_SENTINEL_DO_NOT_USE_ = std::numeric_limits<int32_t>::min(),
  RPC_PROTOCOL_INT_MAX_SENTINEL_DO_NOT_USE_ = std::numeric_limits<int32_t>::max()
};
bool RPC_PROTOCOL_IsValid(int value);
constexpr RPC_PROTOCOL RPC_PROTOCOL_MIN = CS_NOTIFY;
constexpr RPC_PROTOCOL RPC_PROTOCOL_MAX = SC_NOTIFY;
constexpr int RPC_PROTOCOL_ARRAYSIZE = RPC_PROTOCOL_MAX + 1;

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* RPC_PROTOCOL_descriptor();
template<typename T>
inline const std::string& RPC_PROTOCOL_Name(T enum_t_value) {
  static_assert(::std::is_same<T, RPC_PROTOCOL>::value ||
    ::std::is_integral<T>::value,
    "Incorrect type passed to function RPC_PROTOCOL_Name.");
  return ::PROTOBUF_NAMESPACE_ID::internal::NameOfEnum(
    RPC_PROTOCOL_descriptor(), enum_t_value);
}
inline bool RPC_PROTOCOL_Parse(
    ::PROTOBUF_NAMESPACE_ID::ConstStringParam name, RPC_PROTOCOL* value) {
  return ::PROTOBUF_NAMESPACE_ID::internal::ParseNamedEnum<RPC_PROTOCOL>(
    RPC_PROTOCOL_descriptor(), name, value);
}
// ===================================================================

class PB_CS_NOTIFY final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:RPC_PACKET.PB_CS_NOTIFY) */ {
 public:
  inline PB_CS_NOTIFY() : PB_CS_NOTIFY(nullptr) {}
  ~PB_CS_NOTIFY() override;
  explicit PROTOBUF_CONSTEXPR PB_CS_NOTIFY(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  PB_CS_NOTIFY(const PB_CS_NOTIFY& from);
  PB_CS_NOTIFY(PB_CS_NOTIFY&& from) noexcept
    : PB_CS_NOTIFY() {
    *this = ::std::move(from);
  }

  inline PB_CS_NOTIFY& operator=(const PB_CS_NOTIFY& from) {
    CopyFrom(from);
    return *this;
  }
  inline PB_CS_NOTIFY& operator=(PB_CS_NOTIFY&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const PB_CS_NOTIFY& default_instance() {
    return *internal_default_instance();
  }
  static inline const PB_CS_NOTIFY* internal_default_instance() {
    return reinterpret_cast<const PB_CS_NOTIFY*>(
               &_PB_CS_NOTIFY_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(PB_CS_NOTIFY& a, PB_CS_NOTIFY& b) {
    a.Swap(&b);
  }
  inline void Swap(PB_CS_NOTIFY* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(PB_CS_NOTIFY* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  PB_CS_NOTIFY* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<PB_CS_NOTIFY>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const PB_CS_NOTIFY& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const PB_CS_NOTIFY& from) {
    PB_CS_NOTIFY::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(PB_CS_NOTIFY* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "RPC_PACKET.PB_CS_NOTIFY";
  }
  protected:
  explicit PB_CS_NOTIFY(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kMessageFieldNumber = 1,
  };
  // string message = 1;
  void clear_message();
  const std::string& message() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_message(ArgT0&& arg0, ArgT... args);
  std::string* mutable_message();
  PROTOBUF_NODISCARD std::string* release_message();
  void set_allocated_message(std::string* message);
  private:
  const std::string& _internal_message() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_message(const std::string& value);
  std::string* _internal_mutable_message();
  public:

  // @@protoc_insertion_point(class_scope:RPC_PACKET.PB_CS_NOTIFY)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr message_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_RpcPacket_2eproto;
};
// -------------------------------------------------------------------

class PB_SC_NOTIFY final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:RPC_PACKET.PB_SC_NOTIFY) */ {
 public:
  inline PB_SC_NOTIFY() : PB_SC_NOTIFY(nullptr) {}
  ~PB_SC_NOTIFY() override;
  explicit PROTOBUF_CONSTEXPR PB_SC_NOTIFY(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  PB_SC_NOTIFY(const PB_SC_NOTIFY& from);
  PB_SC_NOTIFY(PB_SC_NOTIFY&& from) noexcept
    : PB_SC_NOTIFY() {
    *this = ::std::move(from);
  }

  inline PB_SC_NOTIFY& operator=(const PB_SC_NOTIFY& from) {
    CopyFrom(from);
    return *this;
  }
  inline PB_SC_NOTIFY& operator=(PB_SC_NOTIFY&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const PB_SC_NOTIFY& default_instance() {
    return *internal_default_instance();
  }
  static inline const PB_SC_NOTIFY* internal_default_instance() {
    return reinterpret_cast<const PB_SC_NOTIFY*>(
               &_PB_SC_NOTIFY_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(PB_SC_NOTIFY& a, PB_SC_NOTIFY& b) {
    a.Swap(&b);
  }
  inline void Swap(PB_SC_NOTIFY* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(PB_SC_NOTIFY* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  PB_SC_NOTIFY* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<PB_SC_NOTIFY>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const PB_SC_NOTIFY& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const PB_SC_NOTIFY& from) {
    PB_SC_NOTIFY::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(PB_SC_NOTIFY* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "RPC_PACKET.PB_SC_NOTIFY";
  }
  protected:
  explicit PB_SC_NOTIFY(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kMessageFieldNumber = 1,
  };
  // string message = 1;
  void clear_message();
  const std::string& message() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_message(ArgT0&& arg0, ArgT... args);
  std::string* mutable_message();
  PROTOBUF_NODISCARD std::string* release_message();
  void set_allocated_message(std::string* message);
  private:
  const std::string& _internal_message() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_message(const std::string& value);
  std::string* _internal_mutable_message();
  public:

  // @@protoc_insertion_point(class_scope:RPC_PACKET.PB_SC_NOTIFY)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr message_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_RpcPacket_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// PB_CS_NOTIFY

// string message = 1;
inline void PB_CS_NOTIFY::clear_message() {
  _impl_.message_.ClearToEmpty();
}
inline const std::string& PB_CS_NOTIFY::message() const {
  // @@protoc_insertion_point(field_get:RPC_PACKET.PB_CS_NOTIFY.message)
  return _internal_message();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void PB_CS_NOTIFY::set_message(ArgT0&& arg0, ArgT... args) {
 
 _impl_.message_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:RPC_PACKET.PB_CS_NOTIFY.message)
}
inline std::string* PB_CS_NOTIFY::mutable_message() {
  std::string* _s = _internal_mutable_message();
  // @@protoc_insertion_point(field_mutable:RPC_PACKET.PB_CS_NOTIFY.message)
  return _s;
}
inline const std::string& PB_CS_NOTIFY::_internal_message() const {
  return _impl_.message_.Get();
}
inline void PB_CS_NOTIFY::_internal_set_message(const std::string& value) {
  
  _impl_.message_.Set(value, GetArenaForAllocation());
}
inline std::string* PB_CS_NOTIFY::_internal_mutable_message() {
  
  return _impl_.message_.Mutable(GetArenaForAllocation());
}
inline std::string* PB_CS_NOTIFY::release_message() {
  // @@protoc_insertion_point(field_release:RPC_PACKET.PB_CS_NOTIFY.message)
  return _impl_.message_.Release();
}
inline void PB_CS_NOTIFY::set_allocated_message(std::string* message) {
  if (message != nullptr) {
    
  } else {
    
  }
  _impl_.message_.SetAllocated(message, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.message_.IsDefault()) {
    _impl_.message_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:RPC_PACKET.PB_CS_NOTIFY.message)
}

// -------------------------------------------------------------------

// PB_SC_NOTIFY

// string message = 1;
inline void PB_SC_NOTIFY::clear_message() {
  _impl_.message_.ClearToEmpty();
}
inline const std::string& PB_SC_NOTIFY::message() const {
  // @@protoc_insertion_point(field_get:RPC_PACKET.PB_SC_NOTIFY.message)
  return _internal_message();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void PB_SC_NOTIFY::set_message(ArgT0&& arg0, ArgT... args) {
 
 _impl_.message_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:RPC_PACKET.PB_SC_NOTIFY.message)
}
inline std::string* PB_SC_NOTIFY::mutable_message() {
  std::string* _s = _internal_mutable_message();
  // @@protoc_insertion_point(field_mutable:RPC_PACKET.PB_SC_NOTIFY.message)
  return _s;
}
inline const std::string& PB_SC_NOTIFY::_internal_message() const {
  return _impl_.message_.Get();
}
inline void PB_SC_NOTIFY::_internal_set_message(const std::string& value) {
  
  _impl_.message_.Set(value, GetArenaForAllocation());
}
inline std::string* PB_SC_NOTIFY::_internal_mutable_message() {
  
  return _impl_.message_.Mutable(GetArenaForAllocation());
}
inline std::string* PB_SC_NOTIFY::release_message() {
  // @@protoc_insertion_point(field_release:RPC_PACKET.PB_SC_NOTIFY.message)
  return _impl_.message_.Release();
}
inline void PB_SC_NOTIFY::set_allocated_message(std::string* message) {
  if (message != nullptr) {
    
  } else {
    
  }
  _impl_.message_.SetAllocated(message, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.message_.IsDefault()) {
    _impl_.message_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:RPC_PACKET.PB_SC_NOTIFY.message)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace RPC_PACKET

PROTOBUF_NAMESPACE_OPEN

template <> struct is_proto_enum< ::RPC_PACKET::RPC_PROTOCOL> : ::std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::RPC_PACKET::RPC_PROTOCOL>() {
  return ::RPC_PACKET::RPC_PROTOCOL_descriptor();
}

PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_RpcPacket_2eproto
